IF NOT EXISTS(SELECT 1 FROM sys.databases WHERE name = 'TEST_DB')
BEGIN
    CREATE DATABASE TEST_DB
END
;
USE TEST_DB
;
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TEST_TARGET_TABLE')
BEGIN
    DROP TABLE TEST_TARGET_TABLE
END
;
CREATE TABLE TEST_TARGET_TABLE(
    DATE_COL     DATETIME,
    NVARCHAR_COL VARCHAR(20),
    INTEGER_COL  INTEGER,
    VARCHAR_COL  VARCHAR(20),
    DECIMAL_COL  DECIMAL(5,2))
;
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TEST_SOURCE_TABLE')
BEGIN
    DROP TABLE TEST_SOURCE_TABLE
END
;
CREATE TABLE TEST_SOURCE_TABLE(
    DATE_COL     DATETIME,
    NVARCHAR_COL VARCHAR(20),
    INTEGER_COL  INTEGER,
    VARCHAR_COL  VARCHAR(20),
    DECIMAL_COL  DECIMAL(5,2))
;
INSERT INTO TEST_SOURCE_TABLE(DATE_COL, NVARCHAR_COL, INTEGER_COL, VARCHAR_COL, DECIMAL_COL) VALUES(GETDATE(), 'Hello你好', 11111.34, '你好', 434.144)
;